version: '3'

services:
  rabbit:
    hostname: rabbit
    image: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=lisa
      - RABBITMQ_DEFAULT_PASS=123456789
    ports:
      - "5672:5672"
      - "15672:15672"
  mongo-db:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - database:/data/db
  import-files:
    image: mongo-import
    build:
      context: .
      dockerfile: Dockerfile.import
    deploy:
      placement:
        constraints:
          - node.hostname == node2
    volumes:
      - files:/tmp/files
  crawler:
    image: crawler
    build:
      context: .
      dockerfile: Dockerfile
    deploy:
      mode: global
    volumes:
      - files:/tmp/files
    depends_on:
      - rabbit

volumes:
  files:
  database:
